version: '3.6'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/cert:/etc/nginx/cert
    restart: always
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
        - '8080:80'
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: php_dev
    ports:
      - '8081:80'
    restart: always

  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: app
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data: {}