version: '3.6'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    restart: always
    depends_on:
      - frontend
      - server
      - php

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    restart: always

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: server
    ports:
      - '8081:80'
    volumes:
      - ./backend:/srv/app
    links:
      - php

  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: php
    volumes:
      - ./backend:/srv/app