version: '3.6'

services:
  reverse-proxy:
    image: traefik:v2.10
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./acme.json:/acme.json
    labels:
      - "--providers.docker.exposedbydefault=false"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`roadwise.duckdns.org`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=default"

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: server
    links:
      - php
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`api.roadwise.duckdns.org`)"
      - "traefik.http.routers.server.entrypoints=websecure"
      - "traefik.http.routers.server.tls.certresolver=default"

  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: php
    labels:
      - "--providers.docker.exposedbydefault=false"