version: '3.6'

services:
  reverse-proxy:
    image: traefik:v2.10
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./acme.json:/acme.json

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    labels:
      - "traefik.http.routers.frontend.rule=Host(`roadwise.duckdns.org`)"

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: server
    volumes:
      - ./backend:/srv/app
    links:
      - php
    labels:
      - "traefik.http.routers.server.rule=Host(`api.roadwise.duckdns.org`)"

  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: php
    volumes:
      - ./backend:/srv/app