api_platform:
    title: Hello API Platform
    version: 1.0.0
    description: This is a sample API built with API Platform
    show_webby: false

    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
                
    patch_formats:
        json:     ['application/merge-patch+json']
        jsonapi:  ['application/vnd.api+json']

    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
