api_platform:
    title: Hello API Platform
    version: 1.0.0
    description: This is a sample API built with API Platform
    show_webby: false

    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
